# Generated by Django 3.1.3 on 2021-11-14 16:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0004_userprofile_secret_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="secret_key",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="secret_api_key",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
