# Generated by Django 3.1.3 on 2022-01-18 15:03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0005_auto_20211114_1619"),
        ("user_profile", "0004_userprofile_trial_period_expired"),
    ]

    operations = []
