# Generated by Django 3.1.3 on 2022-01-25 06:40
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0006_merge_20220118_1503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="trial_period_expired",
            field=models.BooleanField(default=False),
        ),
    ]
