# Generated by Django 4.0.2 on 2022-02-24 11:45
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0007_auto_20220125_0640"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="trial_period_expired",
        ),
    ]
