# Generated by Django 3.1.3 on 2021-02-14 12:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_auto_20210214_1233"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoractivity",
            name="response_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
