# Generated by Django 3.1.3 on 2021-02-14 14:11
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_auto_20210214_1252"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitoractivity",
            name="server_response",
        ),
    ]
