# Generated by Django 3.1.3 on 2021-10-09 10:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0005_remove_monitoractivity_server_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="monitor",
            name="paid_till",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
