# Generated by Django 3.1.3 on 2021-10-09 13:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0006_auto_20211009_1017"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="last_connection_establish",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="monitor",
            name="last_response_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
