# Generated by Django 3.1.3 on 2021-10-09 14:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0007_auto_20211009_1305"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="last_connection_establish",
            field=models.NullBooleanField(),
        ),
    ]
