# Generated by Django 3.1.3 on 2021-10-30 13:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0008_auto_20211009_1400"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="last_response_time_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monitoractivity",
            name="response_time_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
