# Generated by Django 3.1.3 on 2022-01-25 06:40
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0009_auto_20211030_1320"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitor",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="monitor",
            name="paid_till",
        ),
    ]
