# Generated by Django 4.0.2 on 2022-02-24 11:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0010_auto_20220125_0640"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restore",
            old_name="body",
            new_name="commands",
        ),
        migrations.RenameField(
            model_name="restore",
            old_name="headers",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="restore",
            old_name="method",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="restore",
            name="query_params",
        ),
        migrations.AlterField(
            model_name="monitor",
            name="last_connection_establish",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
