# Generated by Django 4.0.2 on 2022-02-24 13:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0011_rename_body_restore_commands_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restore",
            name="commands",
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name="restore",
            name="password",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="restore",
            name="username",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
