# Generated by Django 4.0.2 on 2022-02-24 13:25
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0008_remove_userprofile_trial_period_expired"),
        ("monitoring", "0012_alter_restore_commands_alter_restore_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restore",
            name="created_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="user_profile.userprofile"),
        ),
        migrations.AlterField(
            model_name="restore",
            name="host",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="restore",
            name="monitor",
        ),
        migrations.AddField(
            model_name="restore",
            name="monitor",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="monitoring.monitor"),
        ),
        migrations.AlterField(
            model_name="restore",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="restore",
            name="port",
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
    ]
