# Generated by Django 4.0.2 on 2022-02-24 13:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0013_alter_restore_created_by_alter_restore_host_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restore",
            name="name",
        ),
    ]
