# Generated by Django 4.0.2 on 2022-04-11 14:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0014_remove_restore_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restore",
            name="port",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
